baseURL = "https://briones.io/"
languageCode = "en-us"
title = "christian's blog"

pygmentsStyle = "friendly"
pygmentsCodeFences = true

publishDir = "build"

googleAnalytics = "UA-137386323-1"

[frontmatter]
lastmod = ["lastmod", ":git", ":default"]

[params]
  # Enables custom date format (optional, the default is MM-DD-YYYY)
  # For reference to date and time templating, see:
  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateformatpretty = "2006-01-02"

[taxonomies]
  tag = "tags"

[author]
  name = "Christian Briones"
  github = "cwbriones"
  email = "christian@briones.io"
  twitter = "cwbriones"
